# Generated by Django 5.1.4 on 2026-05-22 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("teachers", "0001_initial"),
        ("transport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("admission_number", models.CharField(max_length=20)),
                ("roll_number", models.CharField(max_length=20)),
                ("class_name", models.CharField(max_length=20)),
                ("section", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("admission_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                (
                    "student_type",
                    models.CharField(
                        choices=[
                            ("day_scholar", "Day Scholar"),
                            ("hostler", "Hostler"),
                        ],
                        default="day_scholar",
                        max_length=15,
                    ),
                ),
                ("hostel_name", models.CharField(blank=True, max_length=100)),
                ("hostel_room", models.CharField(blank=True, max_length=20)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                (
                    "medical_conditions",
                    models.TextField(blank=True, default="None reported"),
                ),
                ("allergies", models.TextField(blank=True, default="None reported")),
                ("religion", models.CharField(blank=True, max_length=50)),
                ("transport_enrolled", models.BooleanField(default=False)),
                ("pickup_point", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="transport.bus",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentees",
                        to="teachers.teacherprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="core.school",
                    ),
                ),
                (
                    "transport_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="transport.route",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("activity", "Activity"), ("award", "Award")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ParentMeeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("attended", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teachers.teacherprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_meetings",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ParentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("relationship", models.CharField(default="Parent", max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_emergency_contact", models.BooleanField(default=False)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("subject", models.CharField(max_length=100)),
                ("is_present", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_attendance",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ConductNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        default="positive",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_conduct_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conduct_notes",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Very Good"),
                            ("C", "Good"),
                            ("D", "Needs Improvement"),
                            ("F", "Poor"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("discipline_score", models.IntegerField(default=90)),
                ("punctuality_score", models.IntegerField(default=90)),
                ("academic_year", models.CharField(default="2025-2026", max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_records",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["school", "class_name", "section"],
                name="students_st_school__c824ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["school", "is_active"], name="students_st_school__714b94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentprofile",
            unique_together={("school", "admission_number")},
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["student", "date"], name="students_da_student_167eb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["school", "date", "subject"],
                name="students_da_school__a161ee_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyattendance",
            unique_together={("student", "date", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="behaviorrecord",
            unique_together={("student", "academic_year")},
        ),
    ]
