"""add_library_tables

Revision ID: 407b8e4db72e
Revises: 3e49d47e468c
Create Date: 2026-05-26 22:22:48.116293

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407b8e4db72e'
down_revision: Union[str, None] = '3e49d47e468c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_books',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('total_copies', sa.Integer(), nullable=False),
    sa.Column('available_copies', sa.Integer(), nullable=False),
    sa.Column('shelf_location', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Available', nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.CHAR(length=36), nullable=True),
    sa.Column('created_by', sa.CHAR(length=36), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=36), nullable=True),
    sa.Column('school_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_library_books_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_books'))
    )
    op.create_index('idx_library_books_school_category', 'library_books', ['school_id', 'category'], unique=False)
    op.create_index('idx_library_books_school_title', 'library_books', ['school_id', 'title'], unique=False)
    op.create_index(op.f('ix_library_books_is_active'), 'library_books', ['is_active'], unique=False)
    op.create_index(op.f('ix_library_books_school_id'), 'library_books', ['school_id'], unique=False)
    op.create_table('library_issues',
    sa.Column('book_id', sa.CHAR(length=36), nullable=False),
    sa.Column('student_id', sa.CHAR(length=36), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('fine_amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Issued', nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.CHAR(length=36), nullable=True),
    sa.Column('created_by', sa.CHAR(length=36), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=36), nullable=True),
    sa.Column('school_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['library_books.id'], name=op.f('fk_library_issues_book_id_library_books')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_library_issues_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_library_issues_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_issues'))
    )
    op.create_index('idx_library_issues_book', 'library_issues', ['book_id', 'status'], unique=False)
    op.create_index('idx_library_issues_student', 'library_issues', ['student_id', 'status'], unique=False)
    op.create_index(op.f('ix_library_issues_is_active'), 'library_issues', ['is_active'], unique=False)
    op.create_index(op.f('ix_library_issues_school_id'), 'library_issues', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_issues_school_id'), table_name='library_issues')
    op.drop_index(op.f('ix_library_issues_is_active'), table_name='library_issues')
    op.drop_index('idx_library_issues_student', table_name='library_issues')
    op.drop_index('idx_library_issues_book', table_name='library_issues')
    op.drop_table('library_issues')
    op.drop_index(op.f('ix_library_books_school_id'), table_name='library_books')
    op.drop_index(op.f('ix_library_books_is_active'), table_name='library_books')
    op.drop_index('idx_library_books_school_title', table_name='library_books')
    op.drop_index('idx_library_books_school_category', table_name='library_books')
    op.drop_table('library_books')
    # ### end Alembic commands ###
