"""library_issues_use_borrower

Revision ID: a728f523717c
Revises: 407b8e4db72e
Create Date: 2026-05-26 22:35:56.189719

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a728f523717c'
down_revision: Union[str, None] = '407b8e4db72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('library_issues', sa.Column('borrower_id', sa.CHAR(length=36), nullable=True))
    op.add_column('library_issues', sa.Column('borrower_type', sa.String(length=20), nullable=False, server_default='student'))
    op.drop_index('idx_library_issues_student', table_name='library_issues')
    op.create_index('idx_library_issues_borrower', 'library_issues', ['borrower_id', 'status'], unique=False)
    op.drop_constraint('fk_library_issues_student_id_students', 'library_issues', type_='foreignkey')
    op.create_foreign_key(op.f('fk_library_issues_borrower_id_users'), 'library_issues', 'users', ['borrower_id'], ['id'])
    op.execute("UPDATE library_issues SET borrower_id = student_id WHERE borrower_id IS NULL")
    op.alter_column('library_issues', 'borrower_id', nullable=False)
    op.drop_column('library_issues', 'student_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_issues', sa.Column('student_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
    op.drop_constraint(op.f('fk_library_issues_borrower_id_users'), 'library_issues', type_='foreignkey')
    op.create_foreign_key(op.f('fk_library_issues_student_id_students'), 'library_issues', 'students', ['student_id'], ['id'])
    op.drop_index('idx_library_issues_borrower', table_name='library_issues')
    op.create_index(op.f('idx_library_issues_student'), 'library_issues', ['student_id', 'status'], unique=False)
    op.drop_column('library_issues', 'borrower_type')
    op.drop_column('library_issues', 'borrower_id')
    # ### end Alembic commands ###
