"""remove_day_of_week_from_period_configs

Revision ID: 4063fe2bc649
Revises: f19fe354557b
Create Date: 2026-05-26 10:43:42.322824

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4063fe2bc649'
down_revision: Union[str, None] = 'f19fe354557b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_period_configs_unique'), 'period_configs', type_='unique')
    op.create_unique_constraint('uq_period_configs_unique', 'period_configs', ['school_id', 'academic_year_id', 'start_time'])
    op.drop_column('period_configs', 'day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_configs', sa.Column('day_of_week', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10), nullable=True))
    op.drop_constraint('uq_period_configs_unique', 'period_configs', type_='unique')
    op.create_unique_constraint(op.f('uq_period_configs_unique'), 'period_configs', ['school_id', 'academic_year_id', 'start_time', 'day_of_week'])
    # ### end Alembic commands ###
