"""add_max_periods_to_classes

Revision ID: 3e49d47e468c
Revises: 4063fe2bc649
Create Date: 2026-05-26 11:20:50.041214

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e49d47e468c'
down_revision: Union[str, None] = '4063fe2bc649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('max_periods', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'max_periods')
    # ### end Alembic commands ###
