# Generated by Django 5.1.4 on 2026-05-22 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=100)),
                ("qualification", models.CharField(blank=True, max_length=255)),
                ("specialization", models.CharField(blank=True, max_length=255)),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("workload_hours", models.IntegerField(default=0)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("contract", "Contract"),
                        ],
                        default="full-time",
                        max_length=20,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("medical_conditions", models.TextField(blank=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=20)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="core.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "employee_id")},
            },
        ),
        migrations.CreateModel(
            name="AdhocClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                ("section", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("period", models.CharField(max_length=20)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adhoc_classes",
                        to="teachers.teacherprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TeacherClassAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                ("section", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=100)),
                ("is_class_teacher", models.BooleanField(default=False)),
                ("privileges", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_assignments",
                        to="teachers.teacherprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("teacher", "class_name", "section", "subject")},
            },
        ),
    ]
